/home/icb/alejandro.tejada/ot_pert_reproducibility/runs_genot/train_zebrafish.py:162: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="train_zebrafish")
/home/icb/alejandro.tejada/miniforge3/envs/jax/lib/python3.12/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
wandb: Currently logged in as: aletl (modality_translation). Use `wandb login --relogin` to force relogin
wandb: WARNING Path /home/icb/alejandro.tejadata/ot_pert_new/runs_genot/bash_scripts/wandb/ wasn't writable, using system temp directory.
wandb: WARNING Path /home/icb/alejandro.tejadata/ot_pert_new/runs_genot/bash_scripts/wandb/ wasn't writable, using system temp directory
wandb: wandb version 0.17.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.17.0
wandb: Run data is saved locally in /tmp/wandb/run-20240627_115327-ywzwe8w5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run fluent-night-57
wandb: ‚≠êÔ∏è View project at https://wandb.ai/modality_translation/genot_zebrafish
wandb: üöÄ View run at https://wandb.ai/modality_translation/genot_zebrafish/runs/ywzwe8w5
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/icb/alejandro.tejada/ot_pert_reproducibility/runs_genot/train_zebrafish.py", line 182, in run
    test_data = load_data(adata_test, cfg, return_dl=False) if cfg.training.n_test_samples != 0 else {}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/icb/alejandro.tejada/ot_pert_reproducibility/runs_genot/train_zebrafish.py", line 57, in load_data
    for cond in zip(adata.obs["condition"].cat.categories):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/icb/alejandro.tejada/miniforge3/envs/jax/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/icb/alejandro.tejada/miniforge3/envs/jax/lib/python3.12/site-packages/pandas/core/accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/icb/alejandro.tejada/miniforge3/envs/jax/lib/python3.12/site-packages/pandas/core/arrays/categorical.py", line 2898, in __init__
    self._validate(data)
  File "/home/icb/alejandro.tejada/miniforge3/envs/jax/lib/python3.12/site-packages/pandas/core/arrays/categorical.py", line 2907, in _validate
    raise AttributeError("Can only use .cat accessor with a 'category' dtype")
AttributeError: Can only use .cat accessor with a 'category' dtype. Did you mean: 'at'?

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: - 0.012 MB of 0.012 MB uploadedwandb: \ 0.012 MB of 0.029 MB uploadedwandb: | 0.012 MB of 0.029 MB uploadedwandb: / 0.029 MB of 0.029 MB uploadedwandb: üöÄ View run fluent-night-57 at: https://wandb.ai/modality_translation/genot_zebrafish/runs/ywzwe8w5
wandb: ‚≠êÔ∏è View project at: https://wandb.ai/modality_translation/genot_zebrafish
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /tmp/wandb/run-20240627_115327-ywzwe8w5/logs
